name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Codecov
        uses: codecov/codecov-action@v2.0.3