name: Workflow for Codecov Action
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Android Tests
        run: ./gradlew testDebugUnitTestCoverage
      - name: Codecov
        uses: codecov/codecov-action@v2.0.3